// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChz6GAuRu7nWfb2T0U2Zk14z55EftAe1Y',
    appId: '1:938310553411:web:be44f991b783e1d86fe9f6',
    messagingSenderId: '938310553411',
    projectId: 'ayokesitu-34c0a',
    authDomain: 'ayokesitu-34c0a.firebaseapp.com',
    storageBucket: 'ayokesitu-34c0a.appspot.com',
    measurementId: 'G-KNY7X0NKZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_O4TLl8BALwBFqEolnPwcAHjMo2Iz3pY',
    appId: '1:938310553411:android:6de538e27e96be866fe9f6',
    messagingSenderId: '938310553411',
    projectId: 'ayokesitu-34c0a',
    storageBucket: 'ayokesitu-34c0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFawMp1MR-y0vc0Jk-bJ_0Zw6VQPMW1zU',
    appId: '1:938310553411:ios:4b35d9a9dc6edfae6fe9f6',
    messagingSenderId: '938310553411',
    projectId: 'ayokesitu-34c0a',
    storageBucket: 'ayokesitu-34c0a.appspot.com',
    iosBundleId: 'ayokesituv2.ayokesituv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFawMp1MR-y0vc0Jk-bJ_0Zw6VQPMW1zU',
    appId: '1:938310553411:ios:4b35d9a9dc6edfae6fe9f6',
    messagingSenderId: '938310553411',
    projectId: 'ayokesitu-34c0a',
    storageBucket: 'ayokesitu-34c0a.appspot.com',
    iosBundleId: 'ayokesituv2.ayokesituv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChz6GAuRu7nWfb2T0U2Zk14z55EftAe1Y',
    appId: '1:938310553411:web:791e1d5c88e9a70f6fe9f6',
    messagingSenderId: '938310553411',
    projectId: 'ayokesitu-34c0a',
    authDomain: 'ayokesitu-34c0a.firebaseapp.com',
    storageBucket: 'ayokesitu-34c0a.appspot.com',
    measurementId: 'G-7V3P23GJWT',  
  );
}
